#!/usr/bin/env bash

function docker_compose_install {
  local fnm_compose="docker-compose-1.7.1-$(uname -s)"
  cache curl "$fnm_compose" "https://github.com/docker/compose/releases/download/1.7.1/docker-compose-$(uname -s)-$(uname -m)"
  rsync -ia "${BASEBOX_CACHE}/curl/$fnm_compose" "$shome/bin/docker-compose"
  chmod +x "$shome/bin/docker-compose"
}

function bootstrap {
  local shome="${_docker_compose_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      docker_compose_install 
      ;;
  esac
}

bootstrap
