#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.docker_compose')" != "$DOCKER_COMPOSE_VERSION" ]]; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.docker_app')" != "$DOCKER_APP_VERSION" ]]; then
    return 1
  fi
}

main "$@"
