#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      return 0
      ;;

    Linux)
      if [[ "$($shome/script/version | jq -r '.docker_compose')" != "$DOCKER_COMPOSE_VERSION" ]]; then
        return 1
      fi

      return 0
      ;;
  esac
}

main "$@"
