#!/usr/bin/env bash

function _docker_compose_profile {
  local shome="${_docker_compose_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"
}

_docker_compose_profile
