#!/usr/bin/env bash

function main {
  local shome="${_docker_compose_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$(which docker-compose 2>/dev/null || true)" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
