#!/usr/bin/env bash

function version {
  local shome="${_docker_compose_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local ver_compose="$(docker-compose --version 2>&- | awk 'NR == 1 {print $3}' | perl -pe 's{,$}{}' || true)"
  jq -n \
    --arg compose "$ver_compose" \
    '{"docker-compose": $compose}'
}

version "$@"
